services:
  - type: web
    name: linkedin-clone-backend
    env: node
    build:
      path: ./server
      env: production
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGO_URI
        sync: false  # Will be set in Render dashboard
    plan: free
